
name: test-pull
on:
  pull_request:
    branches: master
    types: [synchronize, opened, reopened, ready_for_review]


jobs:
  test-me:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo ${{ github.event.pull_request.mergeable }}
