name: triggers-test

on:
  workflow_run:
    workflows: ["push-to-master"]
    types: 
      - completed

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        env:
          GITHUB_CONTEXT: ${{ github.event.workflow_run.head_commit.id }}
        run: |
          echo my commit sha is: "$GITHUB_CONTEXT"