name: triggers-test

on:
  workflow_run:
    workflows: ["push-to-master"]
    types: 
      - completed

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: |
          echo ${{ github.event.workflow_run.head_commit.id  }}
          echo ${{ github.event.workflow_run.conclusion }}
          