name: percy-test-status

on:
  workflow_run:
    workflows: ["push-to-master"]
    types: 
      - completed
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  percy-test-status:
    if: false == contains(github.event.pull_request.labels.*.name, 'check-percy-results-before-merge') || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
     TRIGGER_EVENT_NAME: ${{ github.event_name }}
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Enable merge if no percy checks pending
        shell: bash
        run:  bash -x  .github/workflows/script.sh